In [1]:
import numpy as np
arr = np.array([10,20,30,40,50,])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
arr =np.array(([1,2],[3,4],[5,6]))
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr = np.array(

In [6]:
arr=np.empty((2,2))
print(arr)

[[0.00000000e+000 8.43373134e-312]
 [8.43373134e-312 8.43373135e-312]]


In [8]:
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
arr = np.ar