In [2]:
import numpy as np
arr = np.arange(1,21)

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(20,)
20
int64


In [13]:
np.random.seed(1)
arr = np.random.randint(50,size=(4,5)).reshape(4,5)
print(arr)
print(arr.itemsize)
print(arr.nbytes)

[[37 43 12  8  9]
 [11  5 15  0 16]
 [ 1 12  7 45  6]
 [25 20 37 18 20]]
4
80


In [30]:
np.random.seed(1)
a = np.random.randint(10,size=(3,4))
print(a)
print(a[:2,:2])
print(a[::2])
print(a[:,::-1])

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8]
 [0 0]]
[[5 8 9 5]
 [6 9 2 4]]
[[5 9 8 5]
 [7 1 0 0]
 [4 2 9 6]]
